=== northeastchen/TPs_M2/TPXML1/xsd/famille.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- famille.xsd -->
<xs:schema targetNamespace="http://www.istic.fr/schema/famille"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fami="http://www.istic.fr/schema/famille"
	elementFormDefault="qualified">

	<xs:element name="famille">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="note" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:choice>
					<xs:element ref="fami:famille" minOccurs="0" maxOccurs="10" />
					<xs:element ref="fami:animal" maxOccurs="3" />
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="responsable" type="xs:NMTOKEN" use="required" />
			<xs:attribute name="nom" type="fami:nomType" use="required" />
			<xs:attribute name="id" type="xs:ID" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="animal">
		<xs:complexType>
			<xs:attribute name="id" type="xs:ID" use="required" />
			<xs:attribute name="nom" type="fami:nomType" />
			<xs:attribute name="date-naissance" type="xs:date" />
			<xs:attribute name="sexe">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="M|F|Inconnu" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="espece" type="xs:string" use="required" />
			<xs:attribute name="taille" >
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="3000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="poids" >
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="3000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="nomType">
		<xs:annotation>
			<xs:documentation>Type qui repr√©sente un nom</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="3" />
			<xs:maxLength value="20" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== northeastchen/TPs_M2/TPXML1/xml/familleAvecSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  familleAvecXSD.xml -->
<famille xmlns="http://www.istic.fr/schema/famille"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.istic.fr/schema/famille ../xsd/famille.xsd" 
	xmlns:fami="http://www.istic.fr/schema/famille" 
	responsable="resp2"
	nom="mammifères-marins" 
	id="fm"
	>
	<note>Famille en cours d'instalation</note>
	<famille responsable="resp1" nom="cétacés" id="fc">
		<note>On rajoute la note obligatoire</note>
		<animal id="a1" nom="Flipper" date-naissance="2003-10-23" espece="dauphin" />
		<animal id="b1" nom="Ecco"  date-naissance="1996-12-25" espece="dauphin"/>
		<animal id="c1" nom="Oum" taille="295" poids="190" sexe="F" espece="dauphin"/>
	</famille>
	<famille responsable="resp4" nom="pinnipèdes" id="fp">
		<note>Famille à compléter</note>
		<animal id="a4" nom="Ben"  espece="phoque"/>
		<animal id="b4" nom="Dali"  espece="otarie"/>
		<animal id="c4" nom="Kim" taille="155" poids="80" sexe="M" espece="otarie"/>
	</famille>
</famille>
