=== northeastchen/TPs_M2/TPXML1/dtd/aquarium.dtd
<!--  aquarium.dtd -->
<!ELEMENT aquarium (info?, famille+) >
<!ELEMENT info (#PCDATA | note)* >
<!ELEMENT note (#PCDATA) >
<!ATTLIST aquarium 
	responsable NMTOKEN #REQUIRED
	nom CDATA #IMPLIED 
	>
<!ELEMENT famille (note?, (famille* | animal+)) >
<!ATTLIST famille id ID #REQUIRED>
<!ELEMENT animal EMPTY>
<!ATTLIST animal id ID #REQUIRED>
<!ATTLIST famille 
	nom CDATA #IMPLIED
	responsable NMTOKEN #REQUIRED 
	>
<!ATTLIST animal 
	nom CDATA #IMPLIED
	sexe  (F | M) 'F'
    date-naissance CDATA #IMPLIED
    poids CDATA #IMPLIED
    taille CDATA #IMPLIED
    espece  NMTOKEN #REQUIRED 
    >

=== northeastchen/TPs_M2/TPXML1/xml/monaquarium.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aquarium SYSTEM "../dtd/aquarium.dtd" >
<aquarium responsable="ChefAquarium" nom="super aquarium">
	<info>
		Une super info :
		<note>c'est une super note ! </note>
		Et là c'est la fin de l'info après la note.
	</info>

	<famille id="f1" responsable="chef1">
		<animal espece="poisson" id="p1" nom="goujon" />
		<animal espece="poisson" id="p2" nom="gardon" />
	</famille>

	<famille id="f2" responsable="chef2">
		<animal espece="crustacés" id="c1" nom="crabe" />
		<animal espece="crustacés" id="c2" nom="crevette" />
		<animal espece="crustacés" id="c3" nom="langoustine" />
	</famille>

	<famille id="f3" responsable="chef3">
		<animal espece="Mollusque" id="m1" nom="bigorneau" />
		<animal espece="Mollusque" id="m2" nom="couteau" />
		<animal espece="Mollusque" id="m3" nom="coque" />
		<animal espece="Mollusque" id="m4" nom="huître" />
	</famille>
</aquarium>
