=== northeastchen/TPs_M2/TPXML1/dtd/famille.dtd
<!--  famille.dtd -->
<!ELEMENT famille (note?, (famille* | animal+)) >
<!ELEMENT note (#PCDATA) >
<!ATTLIST famille id ID #REQUIRED>
<!ELEMENT animal EMPTY>
<!ATTLIST animal id ID #REQUIRED>
<!ATTLIST famille 
	nom CDATA #IMPLIED
	responsable NMTOKEN #REQUIRED 
	>
<!ATTLIST animal 
	nom CDATA #IMPLIED
	sexe  (F | M) 'F'
    date-naissance CDATA #IMPLIED
    poids CDATA #IMPLIED
    taille CDATA #IMPLIED
    espece  NMTOKEN #REQUIRED 
    >

=== northeastchen/TPs_M2/TPXML1/xml/famille-4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE famille SYSTEM "../dtd/famille.dtd">
<?xml-stylesheet type="text/css" href="../css/simple.css"?>

<!-- famille-4.xml -->
<famille responsable="resp2" nom="mammifères-marins" id="fm2">
	<note>Famille en cours d'installation</note>
	<famille responsable="resp1" nom="cétacés" id="fc">
		<animal id="a1" nom="Flipper" date-naissance="2003-10-23"
			espece="dauphin" />
		<animal id="b1" nom="Ecco" date-naissance="1996-12-25" espece="dauphin" />
		<animal id="c1" nom="Oum" taille="295" poids="190" sexe="F"
			espece="dauphin" />
	</famille>
	<famille responsable="resp4" nom="pinnipèdes" id="fp">
		<note>Famille à compléter</note>
		<animal id="a4" nom="Ben" espece="phoque" />
		<animal id="b4" nom="Dali" espece="otarie" />
		<animal id="c4" nom="Kim" taille="155" poids="80" sexe="M"
			espece="otarie" />
	</famille>
	<famille responsable="resp2" id="fm3">
		<animal id="a3" nom="Plaute" taille="3300" poids="3000" espece="baleine" />
	</famille>
</famille>

=== northeastchen/TPs_M2/TPXML1/xml/famille-6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE famille SYSTEM "../dtd/famille.dtd">
<!--  famille-6.xml -->
<famille responsable="resp2" nom="mammifères-marins" id="fm">
	<note>Aquarium en cours d'installation</note>
	<famille responsable="resp1" nom="cétacés" id="fc">
		<animal id="a1" nom="Flipper" date-naissance="2003-10-23" espece="dauphin" />
		<animal id="b1" nom="Ecco"  date-naissance="1996-12-25" espece="dauphin"/>
		<animal id="c1" nom="Oum" taille="295" poids="190" sexe="F" espece="dauphin"/>
	</famille>
	<famille responsable="resp4" nom="pinnipèdes" id="fp">
		<animal id="a4" espece="phoque" nom="Ben"  />
		<animal id="b4" espece="otarie" nom="Dali" />
		<animal id="c4" taille="155" poids="80" sexe="M" espece="otarie" nom="Kim" />
	</famille>
</famille>

=== northeastchen/TPs_M2/TPXML1/xml/famille-7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE famille SYSTEM "../dtd/famille.dtd">
<!--  famille-7.xml -->
<famille id="fm" responsable="Resp" nom="mammifères-marins" >
	<famille responsable="resp1" nom="cétacés" id="fc">
		<animal id="a1" nom="Flipper" date-naissance="2003-10-23" espece="dauphin" />
		<animal id="b1" nom="Ecco"  date-naissance="1996-12-25" espece="dauphin"/>
		<animal id="c1" nom="Oum" taille="295" poids="190" sexe="M" espece="dauphin"/>
	</famille>
	<famille id="fp" responsable="M.Chef" nom="pinnipèdes" >
		<animal id="a4" nom="Ben" espece="phoque" />
		<animal id="b4" nom="Kim" espece="otarie" />
		<animal id="a2" taille="155" poids="80" sexe="M" espece="otarie" nom="Ben" />
	</famille>
</famille>
