=== northeastchen/TPs_M2/TPXML1/dtd/test.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<!ELEMENT commentaire (#PCDATA)>
<!ELEMENT dauphin (nom?, sexe?, taille, poids)>
<!ATTLIST dauphin
	id ID #REQUIRED
	date-naissance CDATA #IMPLIED
>
<!ELEMENT dauphins (dauphin+)>
<!ELEMENT mammifères-marins (dauphins)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT poids (#PCDATA)>
<!ATTLIST poids
	unité CDATA #REQUIRED
	statut CDATA #IMPLIED
>
<!ELEMENT poissons (selaciens)>
<!ELEMENT requin (nom?, sexe?, taille, poids, commentaire?)>
<!ATTLIST requin
	id ID #REQUIRED
	espèce CDATA #REQUIRED
	date-naissance CDATA #IMPLIED
	nom-savant CDATA #IMPLIED
>
<!ELEMENT selaciens (requin+)>
<!ELEMENT sexe (#PCDATA)>
<!ELEMENT taille (#PCDATA)>
<!ATTLIST taille
	unité (cm|kg) 'kg'
>
<!ELEMENT test (mammifères-marins, poissons)>

=== northeastchen/TPs_M2/TPXML1/xml/test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE demo SYSTEM "../dtd/test.dtd" >
<!-- test.xml -->
<test>
        <mammifères-marins>
            <dauphins>
                <dauphin id="jhgtr13"  date-naissance="1997-4-1">
                    <nom>Flipper</nom>
                    <sexe>M</sexe>
                    <taille unité="cm">215</taille>
                    <poids unité="kg">105</poids>
                </dauphin>
                <dauphin id="lkjh45" date-naissance="2003-10-23">
                    <nom>Ecco</nom>
                    <sexe>F</sexe>
                    <taille unité="cm">202</taille>
                    <poids unité="kg">98</poids>
                </dauphin>
                <dauphin id="kjlhy90" date-naissance="1996-12-25">
                    <nom>Oum</nom>
                    <sexe>F</sexe>
                    <taille unité="cm">295</taille>
                    <poids unité="kg" statut="mesure approximative">190<!-- à vérifier --></poids>
                </dauphin>
            </dauphins>
        </mammifères-marins>
        <poissons>
            <selaciens>
                <requin id="plojk09" espèce="marteau" date-naissance="1998-6-5">
                    <nom>Edgar</nom>
                    <sexe>M</sexe>
                    <taille unité="cm">455</taille>
                    <poids unité="kg">540</poids>
                    <commentaire>Nervosité fréquente
                        <![CDATA[<<< explication ??? >>>]]>
                        <!-- à surveiller -->
                    </commentaire>
                </requin>
                <requin id="vgyuh43" espèce="requin bleu" nom-savant="carcharias glaucus" date-naissance="2004-1-13">
                    <nom>Pablo</nom>
                    <sexe>M</sexe>
                    <taille unité="cm">355</taille>
                    <poids unité="kg" statut="">425</poids>
                </requin>
            </selaciens>
        </poissons>
</test>
